baseURL = 'https://tastyhedge.com/'
languageCode = 'en-us'
title = 'TastyHedge'

disableKinds = ["taxonomy", "taxonomyTerm"]

[author]
  name = "Oleksandr Gituliar"
  email = "oleksandr@gituliar.net"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'perldoc'